package com.studio.timeclock4.utils

const val NUMBER_SECONDS_IN_MINUTE = 60
const val NUMBER_MINUTES_IN_HOUR = 60
const val NUMBER_HOURS_IN_DAY = 24
const val NUMBER_NANOSECONDS_IN_MICROSECONDS = 1000

const val NUMBER_MICROSECONDS_IN_MILLISECONDS = 1000
const val NUMBER_MILLISECONDS_IN_SECOND = 1000
const val NUMBER_SECONDS_IN_HOUR = NUMBER_SECONDS_IN_MINUTE * NUMBER_MINUTES_IN_HOUR
const val NUMBER_MICROSECONDS_IN_SECONDS = NUMBER_MICROSECONDS_IN_MILLISECONDS * NUMBER_MILLISECONDS_IN_SECOND
const val NUMBER_NANOSECONDS_IN_SECONDS = NUMBER_NANOSECONDS_IN_MICROSECONDS * NUMBER_MICROSECONDS_IN_SECONDS
const val NUMBER_MINUTES_IN_SECONDS = 1F / 60