name: Android CI

on: [push]
jobs:

  buildTest:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download Dependencies
        run: bash ./gradlew dependencies
      - name: Build with Gradle
        run: bash ./gradlew build check assemble detekt --stacktrace
      - name: Upload Checks
        uses: actions/upload-artifact@v1
        with:
          name: report
          path: ///home/runner/work/TimeClock4/TimeClock4/app/build/reports

  createAPK:
    needs: [buildTest]
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup
        run: |
          echo ${{ secrets.KEYSTORE_BASE64 }} | base64 -d > my-release-key.jks
          printf 'keyAlias=%s\nkeyPassword=%s\nstoreFile=%s\nstorePassword=%s\n' $"${{ secrets.keyAlias }}" $"${{ secrets.keyPassword }}" $"../my-release-key.jks" $"${{ secrets.storePassword }}" >> keystore.properties
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug
        
      - name: Build release APK
        run: bash ./gradlew assembleRelease --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/release
